---
- name: update web, nfs and db servers
  hosts: webservers, nfs, db
  remote_user: ubuntu
  become: yes
  become_user: root
  tasks:
  - name: delete wireshark
    apt:
      name: wireshark
      state: absent
      autoremove: yes

- name: update LB server
  hosts: lb
  remote_user: 'ec2-user'
  become: yes
  become_user: root
  tasks:
  
  - name: delete wireshark-qt
    yum:
      name: wireshark-qt
      state: removed
      autoremove: yes
      # purge: yes
      # autoclean: yes

  - name: delete wireshark
    yum:
      name: wireshark
      state: removed
      autoremove: yes    
