---
- name: update web, nfs and db servers
  hosts: webservers, nfs, db
  remote_user: ubuntu
  become: yes
  become_user: root
  tasks:
  - name: delete reshark-qt
    apt:
      name: wireshark
      state: absent
      purge: yes
      autoremove: yes
      autoclean: yes

- name: update LB server
  hosts: lb
  remote_user: 'ec2-user'
  become: yes
  become_user: root
  tasks:
        
  - name: delete wireshark
    yum:
      name: wireshark
      state: absent
      autoremove: yes    
