[nfs]
172.31.41.240 ansible_ssh_user='ec2-user'

[webservers]
172.31.44.26 ansible_ssh_user='ec2-user'
172.31.47.56 ansible_ssh_user='ec2-user'

[db]
172.31.34.8 ansible_ssh_user='ec2-user' 

[lb]
172.31.39.179  ansible_ssh_user='ubuntu'

